export default function getAllProducts() {
  return [
    {
      id: "NAF-1-07-FMEN-001",
      slug: "nike-air-force-1-07-men",
      name: "Vans Slip On - Checker Board Motif",
      category: "Men's Shoes",
      categorySlug: "men-shoes",
      price: 799000,
      stock: 100,
      imageUrl: "/assets/images/Vans Slip On.png",
      description: `Vans Slip-On dengan motif checkerboard adalah sepatu ikonik yang menampilkan pola kotak-kotak hitam dan putih pada bagian atasnya. Desain slip-on ini tidak menggunakan tali, membuatnya mudah dipakai dan dilepas. Dengan sol karet yang fleksibel dan nyaman, sepatu ini menawarkan kenyamanan serta gaya kasual yang timeless. Cocok untuk berbagai aktivitas sehari-hari, baik untuk tampil santai maupun menambah kesan street style pada penampilan Anda.`,
    },
    {
      id: "NAF-1-07-FMEN-LV8-002",
      slug: "nike-air-force-1-07-lv8-men",
      name: "Converse Chuck - BlackWhite",
      category: "Men's Shoes",
      categorySlug: "men-shoes",
      price: 959000,
      stock: 50,
      imageUrl: "/assets/images/Converse.png",
      description: `Converse Chuck Taylor All Star Black White adalah sepatu klasik yang menghadirkan desain sederhana namun ikonik. Dengan warna hitam di bagian atas dan sol putih yang kontras, sepatu ini memadukan gaya kasual dan stylish. Terbuat dari kanvas yang ringan dan tahan lama, sepatu ini dilengkapi dengan fitur khas Chuck Taylor, seperti logo bintang di sisi dalam dan sol karet yang fleksibel. Desain low-top ini sangat nyaman digunakan sehari-hari dan cocok dipadukan dengan berbagai outfit, dari jeans hingga celana pendek, untuk tampilan yang timeless dan trendi.`,
    },
    {
      id: "NAF-1-07-FWOMEN-003",
      slug: "nike-air-force-1-07-women",
      name: "Tomkins Moonage-Black White",
      category: "Women's Shoes",
      categorySlug: "women-shoes",
      price: 577000,
      stock: 0,
      imageUrl: "/assets/images/Tomkins-BlackWhite.jpg",
      description: `Tomkins Moonage adalah sepatu kasual dengan desain yang modern dan minimalis. Memadukan warna hitam dan putih, sepatu ini menawarkan gaya yang serbaguna dan mudah dipadukan dengan berbagai jenis pakaian. Bagian atas sepatu terbuat dari material yang kuat dan nyaman, sementara solnya yang ringan memberikan kenyamanan maksimal saat digunakan seharian. Dengan tampilan yang simpel namun stylish, Tomkins Moonage cocok untuk berbagai kesempatan, baik untuk aktivitas santai maupun untuk memberi sentuhan casual pada penampilan sehari-hari.`,
    },
    {
      id: "NAF-1-07-FMEN-LV8-004",
      slug: "warrior-men",
      name: "Warrior - Neo Spartan",
      category: "Men's Shoes",
      categorySlug: "men-shoes",
      price: 899000,
      stock: 52,
      imageUrl: "/assets/images/Warrior.png",
      description: ` Warrior Neo Spartan adalah sepatu yang dirancang untuk performa dan kenyamanan. Dengan desain futuristik dan dinamis dengan tema Spartan, sepatu ini menggabungkan material berkualitas tinggi yang tahan lama dan breathable, memastikan kenyamanan maksimal selama aktivitas intens.`,
    },

    {
      id: "NAF-1-07-FMEN-LV8-005",
      slug: "ventella-men",
      name: "Ventella - Black Natural",
      category: "Men's Shoes",
      categorySlug: "men-shoes",
      price: 1199000,
      stock: 0,
      imageUrl: "/assets/images/ventella.png",
      description: `Sepatu dengan desain minimalis yang memadukan elemen klasik dan modern. Bagian atasnya terbuat dari material berkualitas dengan warna hitam yang elegan, dipadukan dengan aksen natural pada sol atau detail lainnya yang memberikan sentuhan hangat dan organik. Sepatu ini menawarkan kenyamanan dan daya tahan, cocok untuk dipakai sehari-hari baik dalam suasana santai maupun semi-formal. Dengan gaya yang fleksibel, Ventella Black Natural mudah dipadukan dengan berbagai outfit, membuatnya pilihan yang sempurna untuk gaya kasual yang tetap berkelas.`,
    },

    {
      id: "NAF-1-07-FWOMEN-006",
      slug: "cWomen-women",
      name: "Converse - Pink Natural",
      category: "Women's Shoes",
      categorySlug: "women-shoes",
      price: 577000,
      stock: 47,
      imageUrl: "/assets/images/cWomen.png",
      description: `sepatu bergaya klasik dengan sentuhan feminin dan lembut. Warna pink yang menawan dipadukan dengan elemen natural pada sol atau detail lainnya, menciptakan tampilan yang fresh dan casual. Terbuat dari bahan kanvas yang ringan dan nyaman, sepatu ini dilengkapi dengan sol karet khas Converse yang tahan lama.`,
    },
  ];
}
